# .github/workflows/build.yml
name: Build QwarkSMP Launcher
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build_all.sh
      
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: build.bat
      
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build_all.sh
